---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: odoo
  name: odoo-data
  namespace: odoo
  annotations:
    appuio.ch/backup: "true"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: odoo
  name: odoo-addons-pv-claim
  namespace: odoo
  annotations:
    appuio.ch/backup: "true"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi